name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run pyright
      uses: jakebailey/pyright-action@v1
